---
apiVersion: v1
kind: Pod
metadata:
  name: ssh-honeypot
  labels:
    app.kubernetes.io/name: ssh-honeypot
spec:
  containers:
    - name: ssh-honeypot
      image: jamescallaghan1987/insecure_ssh:latest
      imagePullPolicy: Always
      ports:
        - name: ssh-port
          containerPort: 22
---
kind: Service
apiVersion: v1
metadata:
  name: ssh-honeypot
spec:
  selector:
    app.kubernetes.io/name: ssh-honeypot
  ports:
    - protocol: TCP
      name: ssh-honeypot
      port: 22
      targetPort: 22