hub:
  allowNamedServers: false
  redirectToServer: false
  services:
    binder:
      apiToken: "a9dcb35bbe860456d1d26782045d5f5a72f06856673e5a84c0fafb2b5290eb82"
  config:
    JupyterHub:
      authenticator_class: dummy


singleuser:
  image:
    name: jupyter/pyspark-notebook
    tag: latest
  defaultUrl: "/lab"
  storage:
    type: none